import type { Metadata } from "next";
import { Archivo_Narrow, Inter } from "next/font/google";
import "./globals.css";
import GuestHeader from "./libs/guest-session/Header";
import GuestFooter from "./libs/guest-session/Footer";

const inter = Inter({ subsets: ["latin"] });
const archivoNarrow = Archivo_Narrow({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tournament",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GuestHeader />
        {children}
        <GuestFooter />
      </body>
    </html>
  );
}
